### ISSUE TITLE
"org_id": conflicts with folder_id

### ISSUE THREAD

**Issue by kodeine** [tuanchris/modern-data-stack#2]
Hello,
I am getting the following error. Any idea's what am i missing?

<img width="528" alt="image" src="https://user-images.githubusercontent.com/8620059/157767837-8b3e0486-998c-4db5-9944-afdb3ebeae1a.png">

Seems like it works fine on `hashicorp/google v3.71.0` but not on 4.xx

**Comment by tfbecker** [comment]
i have the same problem....

**Comment by kodeine** [comment]
Use org_id = null
